### ISSUE TITLE
Fix the charset

### ISSUE THREAD

**Issue by hi-im-alex** [AlexPiccana/color-generator#4]
Replace

```
<meta charset="utf=8">
```

with

```
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
```

**Comment by aahern** [comment]
![image](https://user-images.githubusercontent.com/14994493/51531241-d27c3980-1e34-11e9-9bdd-1e8213a9fe18.png)
example of issue

not 100% sure if the html fix will work, so if it doesn't investigate further

**Comment by hi-im-alex** [comment]
Fixed! :D
